-- Backfills cards.design_features for rows sent before that column existed
-- (034_cards_design_features.sql) — a generic, non-specific blurb, since the
-- original draft data needed to generate a real per-card description no
-- longer exists for these older sends. Only touches rows still null, so it
-- never overwrites a real description generated by the app going forward.
update cards
set design_features = 'Designed using CardDrop in four easy steps — Take a Photo, Style It, Write It, Send It.'
where design_features is null;
